language: node_js
node_js:
  - "12"

cache: yarn

env:
  - NODE_ENV: test

branches:
  only:
    - develop
    - master

install:
  - yarn

before_script:
  - yarn test:coverage
  - yarn
  - yarn start:lambda&

script:
  - sleep 10
  # Requires Apollo Graph Manger Team Plan ;_;
  # - yarn schema:check -- --tag=$TRAVIS_BRANCH
  - - yarn schema:push -- --tag=$TRAVIS_BRANCH
# Used to deploy service directly to AWS Lambda using the Serverless Framework
# Only use if you want to manually deploy in CI instead of using the Serverless GitHub App
# deploy:
#  # deploy develop to the staging environment
#  - provider: script
#    skip_cleanup: true
#    script: yarn deploy:dev
#    on:
#      node: "12"
#      branch: develop
#  # deploy master to production
#  - provider: script
#    skip_cleanup: true
#    script:
#      - yarn deploy:prod
#    on:
#      node: "12"
#      branch: master
